"""dev_bridge 鉴权测试（PRD §9.1 威胁模型）。

dev_bridge 暴露的是**完整 Command Bus**（含 DeleteAsset / InstallPlugin /
UpdateConfig）。此前只有 CORS 白名单——那只挡浏览器，挡不住本机任何进程
或本地 Agent，而「本机运行的外部 Agent」正是 §9.1 的威胁模型。
"""

from __future__ import annotations

import importlib
import os
from typing import Any

import pytest


class _FakeHandler:
    """最小 handler 替身：只需要 .headers.get。"""

    def __init__(self, auth: str | None) -> None:
        self.headers: dict[str, Any] = {}
        if auth is not None:
            self.headers["Authorization"] = auth

    def _get(self, key: str, default: str = "") -> str:
        return str(self.headers.get(key, default))


class _Headers(dict):  # type: ignore[type-arg]
    def get(self, key: str, default: str = "") -> str:  # type: ignore[override]
        return str(super().get(key, default))


def _handler(auth: str | None) -> Any:
    h = _FakeHandler(None)
    h.headers = _Headers()
    if auth is not None:
        h.headers["Authorization"] = auth
    return h


def _reload_bridge(monkeypatch: pytest.MonkeyPatch, **env: str) -> Any:
    for key in (
        "STEPWORK_DEV_BRIDGE_TOKEN",
        "STEPWORK_DEV_BRIDGE_NO_AUTH",
    ):
        monkeypatch.delenv(key, raising=False)
    for key, value in env.items():
        monkeypatch.setenv(key, value)
    import worker.dev_bridge as bridge

    return importlib.reload(bridge)


def test_rejects_missing_and_wrong_token(monkeypatch: pytest.MonkeyPatch) -> None:
    bridge = _reload_bridge(monkeypatch, STEPWORK_DEV_BRIDGE_TOKEN="secret-token")
    assert bridge._authorized(_handler("Bearer secret-token")) is True
    assert bridge._authorized(_handler("Bearer wrong")) is False
    assert bridge._authorized(_handler(None)) is False
    # 非 Bearer 前缀不接受
    assert bridge._authorized(_handler("secret-token")) is False


def test_token_autogenerated_when_env_absent(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """未配置时随机生成，而不是退化成「空令牌 = 放行」。"""
    bridge = _reload_bridge(monkeypatch)
    assert bridge.AUTH_TOKEN, "必须自动生成令牌"
    assert len(bridge.AUTH_TOKEN) >= 16
    assert bridge.AUTH_DISABLED is False
    assert bridge._authorized(_handler(None)) is False


def test_auth_can_be_disabled_only_explicitly(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """关闭鉴权必须显式声明，不能因为「没配 token」就自动放行。"""
    bridge = _reload_bridge(monkeypatch, STEPWORK_DEV_BRIDGE_NO_AUTH="1")
    assert bridge.AUTH_DISABLED is True
    assert bridge._authorized(_handler(None)) is True


def teardown_module(_m: Any) -> None:
    """还原模块状态，避免影响其它测试。"""
    os.environ.pop("STEPWORK_DEV_BRIDGE_TOKEN", None)
    os.environ.pop("STEPWORK_DEV_BRIDGE_NO_AUTH", None)
    import worker.dev_bridge as bridge

    importlib.reload(bridge)
